name: Build starters using JUnit SNAPSHOT
on:
  push:
  schedule:
  - cron: '0 6 * * *'
jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'JUnit 5 SNAPSHOT build: Gradle'
        run: cd ${GITHUB_WORKSPACE}/junit5-jupiter-starter-gradle && ./gradlew test --console plain --build-file build-SNAPSHOT.gradle
      - name: 'JUnit 5 SNAPSHOT build: Maven'
        run: cd ${GITHUB_WORKSPACE}/junit5-jupiter-starter-maven && ./mvnw test --batch-mode --file pom-SNAPSHOT.xml
